<?xml version="1.0" encoding="utf-8"?><Database Name="KMIP_DB" Class="DAODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PASHA-4GNPUBNCV\ESQLSERVER;Initial Catalog=KMIP_DB;Integrated Security=True" SettingsObjectName="TSUnion.KMIP.DAO.Properties.Settings" SettingsPropertyName="KMIP_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KMIP_OBJECT" Member="KMIP_OBJECT">
    <Type Name="KMIP_OBJECT">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Attributes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KMIP_OBJECT_ARCHIVE" Member="KMIP_OBJECT_ARCHIVE">
    <Type Name="KMIP_OBJECT_ARCHIVE">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Archived" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>